Algoritmo " conversorR$toUS$"



Var
x,cont,dolar,valor, total : real

Inicio


cont <-1
     escreval ("Quantas vezes você quer converter ? ")
     leia (x)
     enquanto (cont <= x) faca
     escreval ("Quantos R$ você deseja converter em US$ ? ")
     leia (valor)
     dolar <- valor/2.20
      escreval ("RESULTADO : " , dolar:2:3, " US$" )
cont <- cont + 1
     fimenquanto


























Fimalgoritmo