Algoritmo " somador-E-maior"



Var
   cont, n, S , maior, menor , M : inteiro

Inicio
   cont<-1
   S <- 0

   enquanto (cont <= 10) faca

      escreva (" DIGITE O ", cont , " º VALOR : " )
      leia (n)
      se (n > maior)entao
         maior <- n
      fimse
      S <- S + N
      cont<- cont + 1
   fimenquanto
   escreval (" A SOMA DOS VALORES FOI : ", S )
   escreval (" O maior valor digitado foi : ", maior)







Fimalgoritmo